export const skills = [
  "HTML",
  "HTML semantics",
  "Accessibility",
  "CSS Flexbox",
  "CSS Grid",
  "BEM convention",
  "JavaScript: ES6+",
  "Promises, async/await",
  "Local Storage",
  "Fetch, Axios",
  "Error handling",
  "Markdown",
  "Immutability",
  "React",
  "React Hooks",
  "React Router",
  "Redux (Toolkit)",
  "Redux Saga",
  "NPM",
  "Git",
  "Scrum",
  "Trello",
  "Teamwork",
];

export const nextSkills = [
  "TypeScript",
  "React Native",
  "Next JS",
];